spring:
  config:
    import:
      - classpath:/application-db.yml
      - classpath:/application-s3.yml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
# ?? ?? ??
server:
  port: 2222